### ISSUE TITLE
Live URLs need additional parts

### ISSUE THREAD

**Issue by codingconcepts** [zhutik/adyen-api-go#48]
Hey mate,

Just reading through the page on live endpoints (https://docs.adyen.com/developers/api-reference/live-endpoints) and think we'll probably need to add in the [random] and [company name] parts into the live URLs...

I'm not sure whether the hpp/cse and hpp URLs need these parts, perhaps you know?

``` go
var Production = Environment{
	Name:      EnvironmentProduction,
	apiURL:    "https://%s-%s-pal-live.adyen.com/pal/servlet",
	clientURL: "https://%s-%s-live.adyen.com/hpp/cse/js/",
	hppURL:    "https://%s-%s-live.adyen.com/hpp/",
}
```

I propose we either add these as parameters to the `ParseEnvironment` function, or create a `MakeEnvironment` function, what do you think?

**Comment by zhutik** [comment]
Hi, I was not aware they change endpoints for live environment...

For sure, we need to allow such URLs to be constructed. Maybe let's create `MakeEnvironment` function (as you suggested) and update docs, who to switch from test to live environment

**Comment by zhutik** [comment]
Closed by https://github.com/zhutik/adyen-api-go/pull/49
