### ISSUE TITLE
adyen.execute deferred error is ignored

### ISSUE THREAD

**Issue by codingconcepts** [zhutik/adyen-api-go#50]
In order to use errors in a defer statement (for closing etc.), the return parameter needs to be named.

**Comment by zhutik** [comment]
Hi, are you referring to this code?

```
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() {
		err = resp.Body.Close()
	}()
```

To be honest, I'm not sure what is the best way to communicate this error back... Also, not sure what is the change of erroring during closing this resource

**Comment by codingconcepts** [comment]
Hey mate, yep, that’s the one.

The chances are fairly slim as it’s just a standard http/net type with nothing funky going on but it’s still good practice to do something with it of course.

The real problem here is the fact we’re overwriting an error we care about (providerResponse.handleHTTPError()) with the deferred close error and losing it.

If we moved that concern out of here and perhaps into the calling Authorise method, we could rename the err param and reintroduce th defer.

**Comment by zhutik** [comment]
What about something like this?

```
	defer func() {
		closeErr := resp.Body.Close()
                 if closeErr != nil {
			a.Logger.Fatal(closeErr)
		}
	}()
```

This would allow to catch error in logs and not to override one `(providerResponse.handleHTTPError())`

**Comment by codingconcepts** [comment]
That’ll kill the application :P  A log.Printf() might be a safer bet!

**Comment by zhutik** [comment]
@codingconcepts I've created a PR https://github.com/zhutik/adyen-api-go/pull/51 can you please check?
