### ISSUE TITLE
Add executeThreeD value to AdditionalData

### ISSUE THREAD

**Issue by sywesk** [zhutik/adyen-api-go#63]
Hello,

Would it be possible to add the "executeThreeD" element to the `AdditionalData` struct ? So that we may manually force the 3D secure authorisation process.

[https://docs.adyen.com/developers/risk-management/3d-secure#authorisethe3dsecurepayment](https://docs.adyen.com/developers/risk-management/3d-secure#authorisethe3dsecurepayment)

Thank you :)

**Comment by zhutik** [comment]
Sure, I will take a look and try perform a change ASAP

**Comment by zhutik** [comment]
@sywesk please check PR - https://github.com/zhutik/adyen-api-go/pull/64 and comment out if it make sense to you

**Comment by sywesk** [comment]
I tried to use ExecuteThreeD,  but as it's a `stringBool` which is a private type of your package, i cannot set it to true / false in the request object. Shall we add a `NewStringBool(bool)` method or export the `stringBool` type ?

**Comment by zhutik** [comment]
I suggest adding `NewStringBool`. This type is supposed to be internal to package, to work with Adyen "boolean" values in API.

**Comment by sywesk** [comment]
@zhutik I opened #65 to add this function
