### ISSUE TITLE
Deprecate in favor of the official lib

### ISSUE THREAD

**Issue by deepu105** [zhutik/adyen-api-go#85]
Hi guys,

first of all, thank you for building and maintaining this. It is awesome. We recently published the official go libs for the Adyen platform https://github.com/Adyen/adyen-go-api-library

Would you be willing to deprecate this lib in favor of the official ones?

Full disclosure: I work for Adyen as a dev advocate

**Comment by deepu105** [comment]
Also contributions, suggestions are welcome on the official lib

**Comment by zhutik** [comment]
@deepu105 I'm super happy to hear that Adyen released their official version!

I'll update README for this library with the deprecation notice and the link to the office library, thanks for letting me know!

**Comment by deepu105** [comment]
Thank you @zhutik appreciate it. Do let us know if you have any feedback/suggestions on the library. And would you know how many people use your lib currently? just to know how popular Go is among people using Adyen platform

**Comment by nirajjayant** [comment]
@deepu105 thats great news! excited to use the library!
